export const FETCH_PRODUCTS = 'GET_PRODUCTS';
export const FETCH_PRODUCTS_DONE = 'GET_PRODUCTS_COMPLETED';
export const INCREMENT_BALANCE = 'ADD_BALANCE';
export const INCREMENT_BALANCE_DONE = 'ADD_BALANCE_COMPLETED';
export const DECREMENT_BALANCE = 'DEDUCT_BALANCE';
export const BUY_PRODUCT = 'BUY_ITEM';
export const BUY_PRODUCT_DONE = 'BUY_ITEM_COMPLETE';
