export const GET_PRODUCT = "GET_PRODUCTS";
export const GET_PRODUCT_DONE = "GET_PRODUCTS_COMPLETED";
export const ADD_BALANCE = "ADD_BALANCE";
export const ADD_BALANCE_DONE = "ADD_BALANCE_COMPLETED";
export const DEDUCT_BALANCE = "DEDUCT_BALANCE";
export const BUY_ITEM = "BUY_ITEM";
export const BUY_ITEM_DONE = "BUY_ITEM_COMPLETE";
